//
//  SearchModels.swift
//  Apple Music
//
//  Created by Vlad Lytvynets on 18.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search{
    
    enum Something{
        
        struct Request{
            enum RequestType {
                case some
                case getTracks(searchText: String)
                case getVideo
            }
        }
        
        struct Response{
            enum ResponseType {
                case some
                case presentTrack(searchResponse: SearchResponse?)
                case presentVideo
            }
        }
        
        struct ViewModel{
            enum ViewModelData {
                case some
                case displayTrack(searchViewModel: SearchViewModel)
                case viewVideo
            }
        }
    }
}


struct SearchViewModel {
    struct Cell: TrackCellViewModel {
        var iconUrlString: String?
        var trackName: String
        var collectionName: String
        var artistName: String
        var previewUrl: String?
    }
    
    let cells: [Cell]
}

