//
//  SearchViewController.swift
//  Apple Music
//
//  Created by Vlad Lytvynets on 18.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchDisplayLogic: class{
    func displaySomething(viewModel: Search.Something.ViewModel.ViewModelData)
}

class SearchViewController: UIViewController, SearchDisplayLogic{
    
    weak var tabBarDelegate: MainTabBarControllerDelegate?
    private lazy var footerView = FooterView()
    private var searchViewModel = SearchViewModel.init(cells: [])
    private var timer: Timer?
    let searchController = UISearchController(searchResultsController: nil)
    var networkmanager = NetworkManager()
    var interactor: SearchBusinessLogic?
    var router: (NSObjectProtocol & SearchRoutingLogic & SearchDataPassing)?
    var tracks = [Track]()
    
    @IBOutlet weak var table: UITableView!
    
    //MARK: - Setup
    private func setup(){
        let viewController        = self
        let interactor            = SearchInteractor()
        let presenter             = SearchPresenter()
        let router                = SearchRouter()
        viewController.interactor = interactor
        viewController.router     = router
        interactor.presenter      = presenter
        presenter.viewController  = viewController
        router.viewController     = viewController
        router.dataStore          = interactor
    }
    
    
    //MARK: - viewDidLoad
    override func viewDidLoad(){
        super.viewDidLoad()
        setup()
        setupTableView()
        setupSearchBar()
    }
    
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        let keyWindow = UIApplication.shared.connectedScenes
            .filter ({$0.activationState == .foregroundActive})
            .map({$0 as? UIWindowScene})
            .compactMap({$0})
            .first?.windows
            .filter({$0.isKeyWindow}).first
        let tabBarVC = keyWindow?.rootViewController as? MainTabBarController
        tabBarVC?.trackDetailView.delegate = self
    }
    
    
    // MARK: - Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?){
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    
    private func setupSearchBar(){
        navigationItem.searchController = searchController
        navigationItem.hidesSearchBarWhenScrolling = false
        searchController.obscuresBackgroundDuringPresentation = false
        searchController.searchBar.delegate = self
    }
    
    
    private func setupTableView(){
        table.register(UITableViewCell.self, forCellReuseIdentifier: "callId")
        let nib = UINib(nibName: "TrackCell", bundle: nil)
        table.tableFooterView = footerView
        table.register(nib, forCellReuseIdentifier: TrackCell.reuseId)
    }
    
    
    func displaySomething(viewModel: Search.Something.ViewModel.ViewModelData){
        
        switch viewModel{
        case .some:
            print("some view")
            
        case .displayTrack(let searchViewModel):
            self.searchViewModel = searchViewModel
            table.reloadData()
            footerView.hideLoader()
            
        case .viewVideo:
            print("ViewVideo")
            
        case .displayFooterView:
            footerView.showLoader()
        }
    }
}


//MARK: - TableView
extension SearchViewController: UITableViewDelegate, UITableViewDataSource{
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return searchViewModel.cells.count
    }
    
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = table.dequeueReusableCell(withIdentifier: TrackCell.reuseId, for: indexPath) as! TrackCell
        let cellViewModel = searchViewModel.cells[indexPath.row]
        
        print("cellViewModel.ReviewURL:", cellViewModel.previewUrl ?? "")
        cell.trackImage.backgroundColor = .red
        cell.set(viewModel: cellViewModel)
        return cell
    }
    
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let cellViewModel = searchViewModel.cells[indexPath.row]
        print("CellModelView: ", cellViewModel.trackName)
        self.tabBarDelegate?.maximizedTrackDetailController(viewModel: cellViewModel)
        
    }
    
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 84
    }
    
    
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let label = UILabel()
        label.text = "Please enter search term above... "
        label.textAlignment = .center
        label.font = UIFont.systemFont(ofSize: 18, weight: .semibold)
        return label
    }
    
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return searchViewModel.cells.count > 0 ? 0 : 250
    }
}


//MARK: - SearchBarDelegate
extension SearchViewController: UISearchBarDelegate{
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: false, block: { [weak self] (_) in
            self?.interactor?.makeRequest(request: Search.Something.Request.RequestType.getTracks(searchText: searchText))
        })
    }
}


//MARK: - TrackMovingDelegate
extension SearchViewController: TrackMovingDelegate {
    
    private func getTrack(isForwardTrack: Bool) -> SearchViewModel.Cell? {
        guard let indexPath = table.indexPathForSelectedRow else { return nil }
        table.deselectRow(at: indexPath, animated: true)
        var nextIndexPath: IndexPath!
        if isForwardTrack{
            nextIndexPath = IndexPath(row: indexPath.row + 1, section: indexPath.section)
            if nextIndexPath.row == searchViewModel.cells.count{
                nextIndexPath.row = 0
            }
        }else{
            nextIndexPath = IndexPath(row: indexPath.row - 1, section: indexPath.section)
            if nextIndexPath.row == -1 {
                nextIndexPath.row = searchViewModel.cells.count - 1
            }
        }
        
        table.selectRow(at: nextIndexPath, animated: true, scrollPosition: .none)
        let cellViewModel = searchViewModel.cells[nextIndexPath.row]
        return cellViewModel
    }
    
    
    func moveBackTrack() -> SearchViewModel.Cell? {
        return getTrack(isForwardTrack: false)
    }
    
    
    func moveForwardTrack() -> SearchViewModel.Cell? {
        return getTrack(isForwardTrack: true)
    }
}
